{
 "title": "Jira_DevOps_Monitoring",
 "description": "Shows Jira JVM and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "endpoint", "label": "endpoint", "query": "8080" },
   { "name": "job", "label": "job", "query": "jira" },
   { "name": "service", "label": "service", "query": "jira" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "hcllimited-devopscoeart-toolchain"
   },
   {
    "name": "pluginKey",
    "label": "pluginKey",
    "query": "com.atlassian.streams.core,com.pyxis.greenhopper.jira,com.springsource.org.jdom-1.0.0,crowd-rest-application-management,crowd-rest-plugin,io.atlassian.fugue-4.5.0,"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_uptime_gauge",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "format": "clocks",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_uptime_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "{{area}} memory"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_current{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "current"
      },
      {
       "expr": "jvm_threads_peak{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "threads_state",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_deadlocked", "legendFormat": "deadloack_thread" },
      {
       "expr": "jvm_threads_state{state=\"RUNNABLE\",}",
       "legendFormat": "runnable"
      },
      {
       "expr": "jvm_threads_state{state=\"NEW\",}",
       "legendFormat": "new"
      },
      {
       "expr": "jvm_threads_state{state=\"WAITING\",}",
       "legendFormat": "waiting"
      },
      {
       "expr": "jvm_threads_state{state=\"TERMINATED\",}",
       "legendFormat": "terminated"
      },
      {
       "expr": "jvm_threads_state{state=\"BLOCKED\",endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "blocked"
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JIRA Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "total Issues",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jira_total_issues_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Update Issues Per User",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(jira_total_issues_gauge) by (username)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Update Issues Per Project",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jira_total_issues_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
       "legendFormat": "{{projectKey}}"
      }
     ]
    },
    {
     "title": "Web Request",
     "type": "graph",
     "description": "Views of all dashboards increases",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jira_web_requests_gauge[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(jira_request_duration_on_path_sum[1m])) by (path)) / (sum(rate(jira_request_duration_on_path_count[1m])) by (path))",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Common Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attachments",
     "type": "singlestat",
     "description": "Displays the current attachments size",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "jira_total_attachment_size_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "description": "The uptime of the Java virtual machine in milliseconds",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_uptime_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Total Sessions",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jira_total_sessions_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "License expiry",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 4 },
     "format": "d",
     "valueName": "current",
     "targets": [
      {
       "expr": "jira_license_expiry_days_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Maintenance expiry",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jira_maintenance_expiry_days_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
      }
     ]
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "All Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_all_users_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_active_users_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Plugin enabled",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\njira_plugin_enabled_count{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Authorized  Sessions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_authorized_sessions_gauge{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  }
 ]
}