{
 "title": "Gitlab_DevOps_Monitoring",
 "description": "Monitor Gitlab: Memory, Process-Age, Sidekiq queue/Latency, Process Count",
 "tags": [ "gitlab" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "process", "label": "Process", "query": "sidekiq,unicorn" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(process_memory_bytes{name=~\"$process\"}) by (pid, name)",
     "legendFormat": "{{name}}_{{ pid }}"
    }
   ]
  },
  {
   "title": "Process Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "process_age_seconds{name=~\"$process\"}",
     "legendFormat": "{{name}}_{{ pid }}"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_size) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sidekiq_queue_latency", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Process Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(process_count) by (name)", "legendFormat": "{{name}}" }
   ]
  }
 ]
}