{
 "title": "Jenkins_Devops_Monitoring",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "endpoint", "query": "8080" },
   { "name": "job", "label": "job", "query": "jenkins" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "hcllimited-devopscoeart-toolchain"
   },
   { "name": "service", "label": "service", "query": "jenkins" }
  ]
 },
 "panels": [
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_memory_total_used{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_health_check_score{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_offline_value{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_cpu_load{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_builds_count{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_success_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_failure_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_free_value{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_queue_size_value{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Project count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_project_count_value{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Plugins active",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_plugins_active{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Plugins with Update",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_plugins_withUpdate{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total job scheduled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_job_scheduled_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  }
 ]
}