{
 "title": "Gerrit_Devops_Monitoring",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "endpoint", "query": "8080" },
   { "name": "job", "label": "job", "query": "gerrit" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "hcllimited-devopscoeart-toolchain"
   },
   { "name": "service", "label": "service", "query": "gerrit" }
  ]
 },
 "panels": [
  {
   "title": "UpTime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "proc_uptime{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Total_event",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "events_total_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_memory_heap_used{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{heap memory}}"
    },
    {
     "expr": "proc_jvm_memory_non_heap_used{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{non_heap-memory}}"
    }
   ]
  },
  {
   "title": "JVM_thread_live",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_thread_num_live{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "proc_jvm_thread_num_live"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "proc_cpu_usage{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total  CLA check requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "license_cla_check_count_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "license_cla_check_count_total"
    }
   ]
  },
  {
   "title": "Memory_cached",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caches_memory_cached_accounts{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "caches_memory_cached_accounts"
    }
   ]
  },
  {
   "title": "Http _Plugin errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "plugin_error_count_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "plugin_error_count_total"
    },
    {
     "expr": "http_server_error_count_total_total",
     "legendFormat": "http_server_error_count_total_total"
    }
   ]
  },
  {
   "title": "SSH sessions connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sshd_sessions_connected{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "sshd_sessions_connected"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "proc_num_open_fds{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Receivecommits created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "queue_receive_commits_total_scheduled_tasks_count{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "queue_receive_commits_total_scheduled_tasks_count"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_gc_count_MarkSweepCompact{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "jvm_gc_count_MarkSweepCompact"
    },
    {
     "expr": "proc_jvm_gc_time_MarkSweepCompact{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "jvm_gc_time_MarkSweepCompact"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_success_count_total_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "success_count_total_total"
    },
    {
     "expr": "http_server_error_count_total_total{endpoint=\"$endpoint\",job=\"$job\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "server_error_count_total_total"
    }
   ]
  }
 ]
}